## Support this project ☕

If you like this Glassmorphism Cinema project, you can support me via:

| Method | Number |
| :--- | :--- |
| **bKash** | `01704235825` (Personal) |
| **Nagad** | `01704235825` (Personal) |
| **A/C:DENY

*Please mention "MUSIC-D" in the reference.*
